import type { Book } from '../types/resonance';
import type { SuggestedDriveLinkMatch } from './backgroundDriveIdleScannerPlugin';

/**
 * Generates a 14-digit standard Zettelkasten timestamp serial (YYYYMMDDHHmmss)
 */
export function generateZettelkastenSerial(date: Date = new Date()): string {
  const pad = (n: number) => n.toString().padStart(2, '0');
  const year = date.getFullYear();
  const month = pad(date.getMonth() + 1);
  const day = pad(date.getDate());
  const hours = pad(date.getHours());
  const minutes = pad(date.getMinutes());
  const seconds = pad(date.getSeconds());
  return `${year}${month}${day}${hours}${minutes}${seconds}`;
}

/**
 * Creates a clean URL-friendly and Obsidian-friendly slug
 */
export function slugifyTitle(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .trim()
    .replace(/[\s_-]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/**
 * Formats a canonical Zettelkasten link with serial: [[20260818041235-book-slug|Book Title]]
 */
export function formatZettelkastenLink(serial: string, title: string): string {
  const slug = slugifyTitle(title);
  return `[[${serial}-${slug}|${title}]]`;
}

/**
 * Retrieves existing Zettelkasten UID from front matter or generates a stable one
 */
export function getOrAssignZettelSerial(book: Book): string {
  const sidecar = book.sidecarMarkdown || '';
  const match = sidecar.match(/zettelkasten_uid:\s*["']?([0-9]{14})["']?/i) ||
                sidecar.match(/zettel_serial:\s*["']?([0-9]{14})["']?/i);

  if (match && match[1]) {
    return match[1];
  }

  // Derive stable serial from ID or current time
  const numMatches = book.id.match(/\d{10,14}/);
  if (numMatches) {
    const raw = numMatches[0];
    return raw.padEnd(14, '0').slice(0, 14);
  }

  return generateZettelkastenSerial();
}

/**
 * Generates a structured Staging Temporary Markdown file with full Zettelkasten serial linking
 */
export function generateStagingTempMarkdown(
  suggestions: SuggestedDriveLinkMatch[],
  books: Book[]
): string {
  const stagingSerial = generateZettelkastenSerial();
  const dateStr = new Date().toISOString();

  let md = `---
zettelkasten_uid: "${stagingSerial}"
title: "Auto-Discovered Drive Matches (Staging Staged)"
type: "temp-staging-manifest"
created_at: "${dateStr}"
status: "staged-idle-scan"
total_matches: ${suggestions.length}
tags: [zettelkasten, staging, temp, idle-scanner, serial-linking]
---

# 🗂️ Staged Real-File Cloud Matches [ZK: ${stagingSerial}]

> [!abstract] Temporary Staging & Serial Linking Manifest
> **Generated:** ${new Date().toLocaleString()}
> **Scope:** Auto-discovered matching real files from opt-in cloud drives (WebDAV, Filejump, Nextcloud, Downloads).
> **Zettelkasten Index:** \`${stagingSerial}\`

---

## 🔗 Staged Item Matches & Serial Linking Map

`;

  suggestions.forEach((sug, idx) => {
    const targetBook = books.find(b => b.id === sug.bookId);
    const bookTitle = targetBook?.title || sug.bookTitle;
    const bookSerial = targetBook ? getOrAssignZettelSerial(targetBook) : generateZettelkastenSerial();
    const sugSerial = sug.zettelkastenUid || generateZettelkastenSerial();

    md += `### ${idx + 1}. ${formatZettelkastenLink(bookSerial, bookTitle)}\n\n`;
    md += `- **Zettelkasten Serial:** \`${sugSerial}\`\n`;
    md += `- **Parent Vault Note:** ${formatZettelkastenLink(bookSerial, bookTitle)} (\`ZK: ${bookSerial}\`)\n`;
    md += `- **Discovered File:** \`${sug.matchedFilename}\` (${(sug.fileSizeBytes / 1024 / 1024).toFixed(2)} MB, ${sug.format.toUpperCase()})\n`;
    md += `- **Provider & Path:** \`${sug.accountName}\` &rarr; \`${sug.matchedPath}\`\n`;
    md += `- **Confidence Score:** \`${sug.confidenceScore}%\`\n`;
    md += `- **Resolution Status:** \`${sug.status.toUpperCase()}\`\n`;
    md += `- **Serial Link Reference:** \`[[${sugSerial}-${slugifyTitle(sug.matchedFilename)}]]\`\n\n`;
  });

  md += `---

## 📊 Summary Linking Table

| ZK Serial | Vault Item | Discovered Cloud File | Storage Provider | Match % | Status |
| :--- | :--- | :--- | :--- | :--- | :--- |
`;

  suggestions.forEach((sug) => {
    const targetBook = books.find(b => b.id === sug.bookId);
    const bookTitle = targetBook?.title || sug.bookTitle;
    const bookSerial = targetBook ? getOrAssignZettelSerial(targetBook) : generateZettelkastenSerial();
    const sugSerial = sug.zettelkastenUid || generateZettelkastenSerial();

    md += `| \`${sugSerial}\` | ${formatZettelkastenLink(bookSerial, bookTitle)} | \`${sug.matchedFilename}\` | \`${sug.accountName}\` | ${sug.confidenceScore}% | \`${sug.status}\` |\n`;
  });

  md += `\n\n---\n*Auto-generated by Sovereign Library Companion MD & Black Box Zettelkasten Engine.*\n`;

  return md;
}

/**
 * Downloads the temporary staging markdown file directly to user's disk
 */
export function downloadStagingTempMarkdown(
  suggestions: SuggestedDriveLinkMatch[],
  books: Book[]
) {
  const mdContent = generateStagingTempMarkdown(suggestions, books);
  const serial = generateZettelkastenSerial();
  const filename = `_${serial}_idle_scan_staged_matches.temp.md`;

  const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
